census_region_lookup <- function(x){

  lookup <- c(`Atlanta-Sandy Springs-Roswell, GA` = "SA",
    `Austin-Round Rock, TX` = "WSC",
    `Baltimore-Columbia-Towson, MD` = "SA",
    `Birmingham-Hoover, AL` = "ESC",
    `Boston-Cambridge-Newton, MA-NH` = "NE",
    `Buffalo-Cheektowaga-Niagara Falls, NY` = "MA",
    `Charlotte-Concord-Gastonia, NC-SC` = "SA",
    `Chicago-Naperville-Elgin, IL-IN-WI` = "ENC",
    `Cincinnati, OH-KY-IN` = "ENC",
    `Cleveland-Elyria, OH` = "ENC",
    `Columbus, OH` = "ENC",
    `Dallas-Fort Worth-Arlington, TX` = "WSC",
    `Denver-Aurora-Lakewood, CO` = "M",
    `Detroit-Warren-Dearborn, MI` = "ENC",
    `Grand Rapids-Wyoming, MI` = "ENC",
    `Hartford-West Hartford-East Hartford, CT` = "NE",
    `Houston-The Woodlands-Sugar Land, TX` = "ESC",
    `Indianapolis-Carmel-Anderson, IN` = "ENC",
    `Jacksonville, FL` = "SA",
    `Kansas City, MO-KS` = "WNC",
    `Las Vegas-Henderson-Paradise, NV` = "M",
    `Los Angeles-Long Beach-Anaheim, CA` = "P",
    `Louisville/Jefferson County, KY-IN` = "ESC",
    `Memphis, TN-MS-AR` = "ESC",
    `Miami-Fort Lauderdale-West Palm Beach, FL` = "SA",
    `Milwaukee-Waukesha-West Allis, WI` = "ENC",
    `Minneapolis-St. Paul-Bloomington, MN-WI` = "WNC",
    `Nashville-Davidson--Murfreesboro--Franklin, TN` = "ESC",
    `New Orleans-Metairie, LA` = "WSC",
    `New York-Newark-Jersey City, NY-NJ-PA` = "MA",
    `Oklahoma City, OK` = "WSC",
    `Orlando-Kissimmee-Sanford, FL` = "SA",
    `Philadelphia-Camden-Wilmington, PA-NJ-DE-MD` = "MA",
    `Phoenix-Mesa-Scottsdale, AZ` = "M",
    `Pittsburgh, PA` = "MA",
    `Portland-Vancouver-Hillsboro, OR-WA` = "P",
    `Providence-Warwick, RI-MA` = "NE",
    `Raleigh, NC` = "SA",
    `Richmond, VA` = "SA",
    `Riverside-San Bernardino-Ontario, CA` = "P",
    `Rochester, NY` = "MA",
    `Sacramento--Roseville--Arden-Arcade, CA` = "P",
    `Salt Lake City, UT` = "M",
    `San Antonio-New Braunfels, TX` = "WSC",
    `San Diego-Carlsbad, CA` = "P",
    `San Francisco-Oakland-Hayward, CA` = "P",
    `San Jose-Sunnyvale-Santa Clara, CA` = "P",
    `Seattle-Tacoma-Bellevue, WA` = "P",
    `St. Louis, MO-IL` = "M",
    `Tampa-St. Petersburg-Clearwater, FL` = "SA",
    `Virginia Beach-Norfolk-Newport News, VA-NC` = "SA",
    `Washington-Arlington-Alexandria, DC-VA-MD-WV` = "SA")
  
  return(factor(lookup[x], levels = c("SA", "ESC", "WSC", "M", "P", "WNC", "ENC", "MA", "NE")))

}
